id: IBBCBD0C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:00:21+00:00'
last_modified: '2022-06-07T12:11:26.810882+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG869
  title: བོད་ལྗོངས་ཡུལ་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    91F2:
      image_group_id: I1KG920
      title: Volume 1 of bod ljongs yul skor
      total_pages: 254
      order: 1
      base_file: 91F2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
